### ISSUE TITLE
Error: vod:not_Serialized

### ISSUE THREAD

**Issue by NiesmialyGosc** [Rexikon/ipla.tv_downloader#2]
Hi Rexikon,

Hope you're fine:-)

For the following episodes (Episodes 147 - 158 of the series "Przyjaciółki"):
https://www.ipla.tv/wideo/serial/Przyjaciolki/5001717/Sezon-13/5015678/Przyjaciolki-Odcinek-147/2e485c09c4df7a92148e7c4ecaaec83f
......
https://www.ipla.tv/wideo/serial/Przyjaciolki/5001717/Sezon-13/5015678/Przyjaciolki-Odcinek-158/de93d1aa8dc432625f7a664e29a8c6cd

The downloader doesn't work..

It yields a "vod:not_serialized" error.. Any thoughts on how to fix this? (I have no problem with downloading the 1st - 146th episodes.)

Many thanks in advance!
NieśmiałyGość

**Comment by Rexikon** [comment]
Hi NiesmialyGosc,
Please change ua=mipla/23 to ua=mipla_ios/122, should work :)

**Comment by NiesmialyGosc** [comment]
Thank you so much @Rexikon ! I'll have another check when I'm back home.

**Comment by NiesmialyGosc** [comment]
It works perfectly; again, thank you very much Rexikon!!:-) Really appreciated!!

**Comment by NiesmialyGosc** [comment]
Hi Rexikon,

Hope you're doing fine:-) I tried the following values for the "user agent" parameter:

ua=mipla_ios/122
ua=www_iplatv_html5/12345
ua=www_iplatv/12345

but none of them works for the following new episodes..:

https://www.ipla.tv/wideo/serial/W-rytmie-serca/5011030/Sezon-5/5016787/W-rytmie-serca-Odcinek-56/ab66a0d8e7e87249bfce18b04906ff85?seasonId=5016787

https://www.ipla.tv/wideo/serial/Przyjaciolki/5001717/Sezon-14/5016764/Przyjaciolki-Odcinek-170/555b45c4ab90db15fbad365bdcbbec12?seasonId=5016764

Has something changed recently..? Do we have a new value for "ua" or is there a workaround for this?

Thank you again for your help!

Sincerely
NiesmialyGosc
